/**
 * GENERATED by scripts/build-internal-mutation-service.mjs.
 * The private staff project authenticates users and signs requests; every
 * write below takes the public-project script lock at the action boundary.
 */
var PUBLIC_BACKEND_URL = 'PUBLIC_BACKEND_URL';
var SWITCH_PROBE_SHARED_SECRET = 'SWITCH_PROBE_SHARED_SECRET';
var SWITCH_PROBE = 'SWITCH_PROBE';
var SWITCH_PROBE_ACK = 'SWITCH_PROBE_ACK';
var SWITCH_MAINTENANCE = 'SWITCH_MAINTENANCE';
var SWITCH_PROBE_TTL_MS = 120000;
var STAFF_SHEET_DEFINITIONS = SHEET_DEFINITIONS;
var ACTIVITY_SPREADSHEET_NAME_LIMIT_ = 100;

function safeActivitySheetName_(title, eventId) {
  var normalizedTitle = String(title || '')
    .replace(/[\u0000-\u001f\u007f-\u009f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim() || '活动';
  var normalizedEventId = String(eventId || '')
    .replace(/[\u0000-\u001f\u007f-\u009f]/g, '')
    .trim();
  var suffix = normalizedEventId ? ' [' + normalizedEventId.slice(-36) + ']' : '';
  var available = Math.max(1, ACTIVITY_SPREADSHEET_NAME_LIMIT_ - suffix.length);
  return normalizedTitle.slice(0, available).trim() + suffix;
}

function createActivitySpreadsheet_(eventId, title, actor) {
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  var spreadsheet = SpreadsheetApp.create(safeActivitySheetName_(title, eventId));
  if (typeof ADMIN_TRANSACTION_ !== 'undefined' && ADMIN_TRANSACTION_) {
    ADMIN_TRANSACTION_.createdSpreadsheetIds =
      ADMIN_TRANSACTION_.createdSpreadsheetIds || [];
    ADMIN_TRANSACTION_.createdSpreadsheetIds.push(spreadsheet.getId());
  }
  initializeEventSpreadsheet_(spreadsheet);
  spreadsheet.addEditor(normalizedActor);
  return spreadsheet;
}

function upsertActivityCatalogEntry_(registry, event, spreadsheet) {
  var eventId = String(event && event.eventId || '').trim();
  var spreadsheetId = String(
    spreadsheet && typeof spreadsheet.getId === 'function' ? spreadsheet.getId() : ''
  ).trim();
  if (!eventId || !spreadsheetId || spreadsheetId === String(registry.getId())) {
    adminError_('INTEGRITY_ERROR');
  }
  var matches = readAdminRows_(registry, '活动目录').filter(function(entry) {
    return String(entry.eventId || '').trim() === eventId;
  });
  if (matches.length > 1 ||
      (matches.length === 1 &&
       String(matches[0].spreadsheetId || '').trim() !== spreadsheetId)) {
    adminError_('INTEGRITY_ERROR');
  }
  var entry = {
    eventId: eventId,
    spreadsheetId: spreadsheetId,
    sheetName: '活动',
    title: event.title,
    description: event.description,
    status: event.status,
    opensAt: event.opensAt,
    closesAt: event.closesAt,
    location: event.location,
    selectionMode: event.selectionMode,
    minChoices: event.minChoices,
    maxChoices: event.maxChoices,
    seatMode: event.seatMode,
    seatZones: event.seatZones,
    createdAt: event.createdAt,
    updatedAt: event.updatedAt
  };
  var sheet = getRequiredSheet_(registry, '活动目录');
  var existingRowNumber = matches.length === 1 ? matches[0].rowNumber : null;
  var targetRowNumber = existingRowNumber || sheet.getLastRow() + 1;
  var previousValues = existingRowNumber
    ? sheet.getRange(
      existingRowNumber, 1, 1, STAFF_SHEET_DEFINITIONS['活动目录'].length
    ).getValues()[0]
    : null;
  try {
    writeAdminRow_(registry, '活动目录', existingRowNumber, entry);
  } catch (error) {
    try {
      if (previousValues) {
        sheet.getRange(
          targetRowNumber, 1, 1, previousValues.length
        ).setValues([previousValues]);
      } else if (sheet.getLastRow() >= targetRowNumber) {
        sheet.deleteRow(targetRowNumber);
      }
    } catch (rollbackError) {
      adminError_('INTEGRITY_ERROR');
    }
    throw error;
  }
  return entry;
}

function activitySheetUrl_(spreadsheet) {
  var spreadsheetId = typeof spreadsheet === 'string' ? spreadsheet : String(
    spreadsheet && typeof spreadsheet.getId === 'function' ? spreadsheet.getId() : ''
  );
  if (!spreadsheetId) adminError_('INTEGRITY_ERROR');
  return 'https://docs.google.com/spreadsheets/d/' +
    encodeURIComponent(spreadsheetId) + '/edit';
}
var ADMIN_TRANSACTION_ = null;
var ADMIN_MUTATION_ACTIONS_ = {
  'admin.saveDraft': true,
  'admin.finalizeDraft': true,
  'admin.deleteDraft': true,
  'admin.deleteEmptyEvent': true,
  'admin.saveEvent': true,
  'admin.saveSession': true,
  'admin.saveSeatPlan': true,
  'admin.saveQuestion': true,
  'admin.recordAction': true,
  'admin.switchSheet': true
};

function executeInternalActionLocked_(action, payload, actor) {
  var handlers = {
    'staff.getTicket': function() {
      var registry = getRegistrySpreadsheet_();
      var route = requireAttendanceTicketRoute_(registry, payload && payload.token);
      var spreadsheet = getEventSpreadsheet_(registry, route.eventId);
      var projection = attendancePublicProjection_(
        findAttendanceTicket_(spreadsheet, payload && payload.token, route)
      );
      var settings = getAdminSettings(registry);
      var policy = settings && settings.registration &&
        settings.registration.events && settings.registration.events[route.eventId] || {};
      var mode = String(policy.checkInMode || 'session').toLowerCase();
      projection.checkInMode = mode === 'event' || mode === 'none' ? mode : 'session';
      return projection;
    },
    'staff.checkIn': function() {
      return internalStaffCheckInLocked_(payload, actor);
    },
    'admin.getDashboard': function() { return getAdminDashboard_(payload, actor); },
    'admin.saveDraft': function() { return saveAdminDraft_(payload, actor); },
    'admin.finalizeDraft': function() { return finalizeAdminDraft_(payload, actor); },
    'admin.deleteDraft': function() { return deleteAdminDraft_(payload, actor); },
    'admin.deleteEmptyEvent': function() { return deleteEmptyAdminEvent_(payload, actor); },
    'admin.saveEvent': function() { return saveAdminEvent_(payload, actor); },
    'admin.saveSession': function() { return saveAdminSession_(payload, actor); },
    'admin.saveSeatPlan': function() { return saveAdminSeatPlan_(payload, actor); },
    'admin.saveQuestion': function() { return saveAdminQuestion_(payload, actor); },
    'admin.recordAction': function() { return adminRecordAction_(payload, actor); },
    'admin.testSheet': function() { return testAdminSheetConnection_(payload, actor); },
    'admin.switchSheet': function() { return switchInternalAdminSheet_(payload, actor); }
  };
  if (!Object.prototype.hasOwnProperty.call(handlers, action)) {
    return internalMutationFailure_('INTERNAL_REQUEST_DENIED');
  }
  try {
    var execute = function() {
      if (ADMIN_MUTATION_ACTIONS_[action]) {
        var registry = getRegistrySpreadsheet_();
        return {
          ok: true,
          data: runAdminMutationTransaction_(
            registry, registry, action, handlers[action]
          )
        };
      }
      return { ok: true, data: handlers[action]() };
    };
    return ADMIN_MUTATION_ACTIONS_[action] || action === 'staff.checkIn'
      ? withInternalActionScriptLock_(execute)
      : execute();
  } catch (error) {
    if ((!error || !error.publicCode) &&
        typeof console !== 'undefined' && console.error) {
      console.error('Internal action failed', action, error);
    }
    return internalMutationFailure_(error && error.publicCode ? error.publicCode : 'INTERNAL');
  }
}

function withInternalActionScriptLock_(callback) {
  var lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    return callback();
  } finally {
    lock.releaseLock();
  }
}

function internalMutationFailure_(code) {
  var messages = {
    INTERNAL_REQUEST_DENIED: '受保护操作不可用。',
    ADMIN_ACTION_DENIED: '管理员功能不可用。',
    STAFF_ACTION_DENIED: '员工签到不可用。',
    INVALID_REQUEST: '提交信息无效，请检查后重试。',
    NOT_FOUND: '未找到对应记录。',
    CONFLICT: '当前数据状态不允许此操作。',
    CONFIRMATION_REQUIRED: '此操作需要明确确认。',
    SHEET_CONNECTION_FAILED: '无法连接到指定的数据表。',
    INTEGRITY_ERROR: '数据一致性检查失败，请联系管理员。',
    TICKET_INACTIVE: '该凭证当前不可签到。',
    TOKEN_INVALID: '凭证无效或已过期。',
    SESSION_NOT_REGISTERED: '该凭证未报名此场讲座。',
    CHECK_IN_CLOSED: '当前不在此场讲座的签到时间内。',
    CHECK_IN_DISABLED: '此活动不需要签到，二维码仍可用于验票。',
    ALREADY_CHECKED_IN: '此场讲座已完成签到。',
    MAINTENANCE: '系统正在切换数据连接，请稍后重试。',
    LEGACY_MIGRATION_REQUIRED: 'Existing legacy activity data must be migrated before activation.',
    INTERNAL: '请求未能完成，请稍后重试。'
  };
  var safeCode = Object.prototype.hasOwnProperty.call(messages, code) ? code : 'INTERNAL';
  return { ok: false, code: safeCode, message: messages[safeCode] };
}

function adminError_(code) {
  var error = new Error(code);
  error.publicCode = code;
  throw error;
}

function withScriptLock_(callback) {
  return callback();
}

function runAdminMutationTransaction_(registry, spreadsheet, action, callback) {
  if (ADMIN_TRANSACTION_) return callback();
  ADMIN_TRANSACTION_ = {
    action: action,
    entries: [],
    sheets: [],
    seen: {},
    createdSpreadsheetIds: []
  };
  try {
    return callback();
  } catch (error) {
    var failures = rollbackAdminMutationTransaction_();
    if (failures.length) {
      var integrityError = new Error('INTEGRITY_ERROR');
      integrityError.publicCode = 'INTEGRITY_ERROR';
      integrityError.cause = error;
      integrityError.rollbackFailures = failures;
      throw integrityError;
    }
    throw error;
  } finally {
    ADMIN_TRANSACTION_ = null;
  }
}

function journalAdminWrite_(sheet, rowNumber, columnCount, isAppend) {
  if (!ADMIN_TRANSACTION_) return;
  var sheetIndex = ADMIN_TRANSACTION_.sheets.indexOf(sheet);
  if (sheetIndex === -1) {
    ADMIN_TRANSACTION_.sheets.push(sheet);
    sheetIndex = ADMIN_TRANSACTION_.sheets.length - 1;
  }
  var key = sheetIndex + ':' + rowNumber;
  if (ADMIN_TRANSACTION_.seen[key]) return;
  ADMIN_TRANSACTION_.seen[key] = true;
  ADMIN_TRANSACTION_.entries.push({
    sheet: sheet,
    rowNumber: rowNumber,
    isAppend: isAppend === true,
    values: isAppend ? null :
      sheet.getRange(rowNumber, 1, 1, columnCount).getValues()[0]
  });
}

function rollbackAdminMutationTransaction_() {
  var transaction = ADMIN_TRANSACTION_;
  if (!transaction) return [];
  var failures = [];
  for (var index = transaction.entries.length - 1; index >= 0; index -= 1) {
    var entry = transaction.entries[index];
    try {
      if (entry.isAppend) {
        if (entry.sheet.getLastRow() >= entry.rowNumber) {
          entry.sheet.deleteRow(entry.rowNumber);
        }
      } else {
        entry.sheet.getRange(
          entry.rowNumber, 1, 1, entry.values.length
        ).setValues([entry.values]);
      }
    } catch (error) {
      failures.push(error);
    }
  }
  for (var fileIndex = transaction.createdSpreadsheetIds.length - 1;
    fileIndex >= 0; fileIndex -= 1) {
    try {
      DriveApp.getFileById(
        transaction.createdSpreadsheetIds[fileIndex]
      ).setTrashed(true);
    } catch (error) {
      failures.push(error);
    }
  }
  return failures;
}

function getRootConfiguredSpreadsheet_() {
  return getRegistrySpreadsheet_();
}

function getConfiguredSpreadsheet_(registry) {
  return getConfiguredSpreadsheet(registry);
}

function getAdminSettings_(registry) {
  return getAdminSettings(registry);
}

function setAdminSettings_(registry, settings) {
  setSharedSettingValue_(registry, ADMIN_SETTINGS, JSON.stringify(settings || {}));
}

function readRows_(spreadsheet, sheetName) {
  return readRows(spreadsheet, sheetName);
}

function openSpreadsheetById_(spreadsheetId) {
  if (typeof spreadsheetId !== 'string' || !spreadsheetId.trim() ||
      spreadsheetId.length > 256) adminError_('INVALID_REQUEST');
  return SpreadsheetApp.openById(spreadsheetId.trim());
}

function internalStaffCheckInLocked_(payload, actor) {
  var registry = getRegistrySpreadsheet_();
  requireNoSwitchMaintenance_(registry);
  if (!payload || typeof payload !== 'object') {
    adminError_('INVALID_REQUEST');
  }
  var route = requireAttendanceTicketRoute_(registry, payload.token);
  if (String(route && route.status || '').trim().toLowerCase() !== 'active') {
    adminError_('TICKET_INACTIVE');
  }
  var spreadsheet = getEventSpreadsheet_(registry, route.eventId);
  var match = findAttendanceTicket_(spreadsheet, payload.token, route);
  if (match.status !== 'active') adminError_('TICKET_INACTIVE');
  if (String(match.event.status || '').toLowerCase() !== 'live') {
    adminError_('CHECK_IN_CLOSED');
  }
  var settings = getAdminSettings(registry);
  var eventPolicy = settings && settings.registration &&
    settings.registration.events && settings.registration.events[route.eventId] || {};
  var checkInMode = String(eventPolicy.checkInMode || 'session').toLowerCase();
  if (checkInMode !== 'session' && checkInMode !== 'event' && checkInMode !== 'none') {
    checkInMode = 'session';
  }
  if (checkInMode === 'none') adminError_('CHECK_IN_DISABLED');
  var sessionId = '__EVENT__';
  var session = null;
  if (checkInMode === 'session') {
    if (typeof payload.sessionId !== 'string' || !payload.sessionId.trim()) {
      adminError_('INVALID_REQUEST');
    }
    sessionId = payload.sessionId.trim();
    session = match.sessions.filter(function(candidate) {
      return candidate.sessionId === sessionId;
    })[0];
    if (!session) adminError_('SESSION_NOT_REGISTERED');
    var sessionStatus = String(session.status || '').toLowerCase();
    if (sessionStatus !== 'live' && sessionStatus !== 'open') {
      adminError_('CHECK_IN_CLOSED');
    }
  }
  var now = new Date();
  if (checkInMode === 'session' &&
      !isWithinInternalAttendanceWindow_(registry, session, now)) {
    adminError_('CHECK_IN_CLOSED');
  }
  var duplicate = readRows(spreadsheet, '签到记录').some(function(record) {
    return record.registrationId === match.registrationId &&
      record.sessionId === sessionId &&
      String(record.status || '').toLowerCase() === 'checked_in';
  });
  if (duplicate) adminError_('ALREADY_CHECKED_IN');
  var row = {
    checkInId: Utilities.getUuid(),
    registrationId: match.registrationId,
    eventId: match.event.eventId,
    sessionId: sessionId,
    checkedInAt: now.toISOString(),
    checkedInBy: String(actor || '').trim().toLowerCase(),
    status: 'checked_in'
  };
  var sheet = getRequiredSheet_(spreadsheet, '签到记录');
  var values = normalizeRow_('签到记录', row);
  sheet.getRange(sheet.getLastRow() + 1, 1, 1, values.length).setValues([values]);
  return { status: 'checked_in', sessionId: sessionId, checkedInAt: row.checkedInAt };
}

function isWithinInternalAttendanceWindow_(registry, session, now) {
  var startsAt = Date.parse(session.startsAt);
  var endsAt = Date.parse(session.endsAt);
  if (!isFinite(startsAt) || !isFinite(endsAt) || endsAt <= startsAt) return false;
  var settings = getAdminSettings(registry);
  var attendance = settings && settings.attendance && typeof settings.attendance === 'object'
    ? settings.attendance : {};
  var earlyMinutes = Number(attendance.earlyMinutes);
  var lateMinutes = Number(attendance.lateMinutes);
  if (!isFinite(earlyMinutes) || earlyMinutes < 0) earlyMinutes = 60;
  if (!isFinite(lateMinutes) || lateMinutes < 0) lateMinutes = 60;
  var timestamp = now.getTime();
  return timestamp >= startsAt - earlyMinutes * 60000 &&
    timestamp <= endsAt + lateMinutes * 60000;
}

function switchInternalAdminSheet_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true || typeof request.spreadsheetId !== 'string' ||
      !request.spreadsheetId.trim()) {
    adminError_(request.confirm === true ? 'INVALID_REQUEST' : 'CONFIRMATION_REQUIRED');
  }
  var registry = getRegistrySpreadsheet_();
  requireNoSwitchMaintenance_(registry);
  var candidate;
  try {
    candidate = openSpreadsheetById_(request.spreadsheetId);
    validateAdminSpreadsheet_(candidate);
    requireLegacyMigrationPreflight_(candidate);
  } catch (error) {
    if (error && error.publicCode) throw error;
    adminError_('SHEET_CONNECTION_FAILED');
  }
  setSharedSettingValue_(registry, ACTIVE_SPREADSHEET_ID, candidate.getId());
  appendAdminAudit_(
    candidate,
    'SWITCH_ACTIVE_SPREADSHEET',
    'spreadsheet',
    'active',
    actor,
    { previousDataRetained: true, migrationPerformed: false }
  );
  return {
    connected: true,
    sheetName: String(candidate.getName ? candidate.getName() : 'Connected'),
    warning: '旧数据会保留在原数据表；系统不会自动迁移。'
  };
}

var ADMIN_EVENT_STATUSES_ = {
  draft: true, upcoming: true, open: true, closed: true,
  live: true, ended: true, cancelled: true, archived: true
};
var ADMIN_SELECTION_MODES_ = {
  none: true, single: true, all: true, free: true, mixed: true, multiple: true
};
var ADMIN_SEAT_MODES_ = { none: true, self: true, auto: true, zone: true };
var ADMIN_QUESTION_TYPES_ = {
  text: true, textarea: true, number: true, tel: true, email: true,
  date: true, radio: true, checkbox: true, select: true, boolean: true
};
var ADMIN_DRAFT_MAX_JSON_LENGTH_ = 45000;

function ensureActivityDraftRegistry_(registry) {
  var sheet = registry.getSheetByName('活动草稿');
  if (!sheet && typeof registry.insertSheet === 'function') {
    sheet = registry.insertSheet('活动草稿');
  }
  if (!sheet) adminError_('SHEET_CONNECTION_FAILED');
  var headers = STAFF_SHEET_DEFINITIONS['活动草稿'];
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    return;
  }
  var actual = sheet.getRange(1, 1, 1, headers.length).getValues()[0];
  if (!headers.every(function(header, index) { return actual[index] === header; })) {
    adminError_('INTEGRITY_ERROR');
  }
}

function validateActivityDraftDocument_(value) {
  var request = requireAdminObject_(value);
  var event = requireAdminObject_(request.event);
  if (Object.prototype.hasOwnProperty.call(event, 'eventId') ||
      Object.prototype.hasOwnProperty.call(event, 'spreadsheetId') ||
      Object.prototype.hasOwnProperty.call(event, 'sheetUrl')) {
    adminError_('INVALID_REQUEST');
  }
  var title = adminTextField_(event, 'title', '', '');
  if (!title) adminError_('INVALID_REQUEST');
  var selectionMode = String(adminField_(event, 'selectionMode', '', 'none')).toLowerCase();
  var seatMode = String(adminField_(event, 'seatMode', '', 'none')).toLowerCase();
  if (!ADMIN_SELECTION_MODES_[selectionMode] || !ADMIN_SEAT_MODES_[seatMode]) {
    adminError_('INVALID_REQUEST');
  }
  var sessions = Array.isArray(request.sessions) ? request.sessions : [];
  var questions = Array.isArray(request.questions) ? request.questions : [];
  var seatPlan = request.seatPlan && typeof request.seatPlan === 'object' &&
      !Array.isArray(request.seatPlan) ? request.seatPlan : { mode: seatMode, zones: [] };
  sessions.forEach(requireAdminObject_);
  questions.forEach(requireAdminObject_);
  var zones = Array.isArray(seatPlan.zones) ? seatPlan.zones : [];
  zones.forEach(requireAdminObject_);
  var document = {
    event: {
      title: title,
      description: adminTextField_(event, 'description', '', ''),
      status: 'draft',
      opensAt: adminDateField_(adminField_(event, 'opensAt', '', '')),
      closesAt: adminDateField_(adminField_(event, 'closesAt', '', '')),
      location: adminTextField_(event, 'location', '', ''),
      selectionMode: selectionMode,
      minChoices: adminNonNegativeInteger_(adminField_(event, 'minChoices', '', 0)),
      maxChoices: adminNonNegativeInteger_(adminField_(event, 'maxChoices', '', 0)),
      seatMode: seatMode,
      seatMapLabel: adminTextField_(event, 'seatMapLabel', '', '舞台 / 白板'),
      seatZones: Array.isArray(event.seatZones) ? event.seatZones.slice() : [],
      showOpeningCountdown: event.showOpeningCountdown === true,
      showClosingCountdown: event.showClosingCountdown === true,
      cancellationEnabled: event.cancellationEnabled === true,
      seatExchangeEnabled: event.seatExchangeEnabled === true,
      seatHoldsEnabled: event.seatHoldsEnabled === true,
      seatHoldMinutes: adminPositiveInteger_(adminField_(event, 'seatHoldMinutes', '', 5)),
      registrationTimeLimitMinutes: adminNonNegativeInteger_(
        adminField_(event, 'registrationTimeLimitMinutes', '', 5)
      ),
      totalCapacity: adminNonNegativeInteger_(
        adminField_(event, 'totalCapacity', '', 0)
      ),
      checkInMode: adminCheckInMode_(adminField_(event, 'checkInMode', '', 'session'))
    },
    sessions: sessions.map(function(session) {
      var copy = {};
      Object.keys(session).forEach(function(key) {
        if (key !== 'eventId' && key !== 'spreadsheetId' && key !== 'sheetUrl') {
          copy[key] = session[key];
        }
      });
      return copy;
    }),
    seatPlan: {
      mode: String(seatPlan.mode || seatMode).toLowerCase(),
      sessionId: typeof seatPlan.sessionId === 'string' ? seatPlan.sessionId.trim() : '',
      zones: zones.map(function(zone) {
        return {
          name: adminTextField_(zone, 'name', '', ''),
          rows: adminNonNegativeInteger_(adminField_(zone, 'rows', '', 0)),
          seatsPerRow: adminNonNegativeInteger_(
            adminField_(zone, 'seatsPerRow', '', 0)
          )
        };
      })
    },
    questions: questions.map(function(question) {
      var copy = {};
      Object.keys(question).forEach(function(key) {
        if (key !== 'eventId' && key !== 'spreadsheetId' && key !== 'sheetUrl') {
          copy[key] = question[key];
        }
      });
      return copy;
    })
  };
  if (document.event.maxChoices < document.event.minChoices ||
      !ADMIN_SEAT_MODES_[document.seatPlan.mode]) {
    adminError_('INVALID_REQUEST');
  }
  if (document.event.opensAt && document.event.closesAt &&
      Date.parse(document.event.closesAt) <= Date.parse(document.event.opensAt)) {
    adminError_('INVALID_REQUEST');
  }
  if (JSON.stringify(document).length > ADMIN_DRAFT_MAX_JSON_LENGTH_) {
    adminError_('INVALID_REQUEST');
  }
  return document;
}

function readActivityDraft_(registry, draftId) {
  var normalizedId = typeof draftId === 'string' ? draftId.trim() : '';
  if (!normalizedId) adminError_('INVALID_REQUEST');
  var matches = readAdminRows_(registry, '活动草稿').filter(function(row) {
    return String(row.draftId || '').trim() === normalizedId;
  });
  if (matches.length > 1) adminError_('INTEGRITY_ERROR');
  if (!matches.length) return null;
  var parsed;
  try {
    parsed = JSON.parse(String(matches[0].payload || ''));
  } catch (_ignored) {
    adminError_('INTEGRITY_ERROR');
  }
  matches[0].document = validateActivityDraftDocument_(parsed);
  return matches[0];
}

function draftNextStep_(document) {
  if (document.event.selectionMode !== 'none' &&
      document.event.selectionMode !== 'free' && !document.sessions.length) {
    return 'sessions';
  }
  if (document.event.seatMode !== 'none' &&
      (!document.seatPlan.zones || !document.seatPlan.zones.length)) {
    return 'seats';
  }
  if (!document.questions.length) return 'questions';
  return 'confirm';
}

function adminDraftProjection_(row) {
  return {
    draftId: String(row.draftId || ''),
    draft: row.document,
    nextStep: draftNextStep_(row.document),
    createdAt: String(row.createdAt || ''),
    updatedAt: String(row.updatedAt || ''),
    finalizedEventId: String(row.finalizedEventId || '')
  };
}

function saveAdminDraft_(payload, actor) {
  var request = requireAdminObject_(payload);
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    ensureActivityDraftRegistry_(registry);
    requireNoSwitchMaintenance_(registry);
    var existing = request.draftId
      ? readActivityDraft_(registry, request.draftId) : null;
    if (request.draftId && !existing) adminError_('NOT_FOUND');
    if (existing && existing.finalizedEventId) adminError_('CONFLICT');
    var document = validateActivityDraftDocument_(request);
    var now = new Date().toISOString();
    var row = {
      draftId: existing ? existing.draftId : Utilities.getUuid(),
      payload: JSON.stringify(document),
      createdBy: existing ? existing.createdBy : normalizedActor,
      createdAt: existing ? existing.createdAt : now,
      updatedAt: now,
      finalizedEventId: existing ? existing.finalizedEventId : ''
    };
    writeAdminRow_(registry, '活动草稿', existing && existing.rowNumber, row);
    row.document = document;
    appendAdminAudit_(
      registry,
      existing ? 'UPDATE_ACTIVITY_DRAFT' : 'CREATE_ACTIVITY_DRAFT',
      'activity_draft',
      row.draftId,
      normalizedActor,
      { title: document.event.title }
    );
    return adminDraftProjection_(row);
  });
}

function finalizeAdminDraft_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true) adminError_('CONFIRMATION_REQUIRED');
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    ensureActivityDraftRegistry_(registry);
    requireNoSwitchMaintenance_(registry);
    var draft = readActivityDraft_(registry, request.draftId);
    if (!draft) adminError_('NOT_FOUND');
    if (draft.finalizedEventId) {
      var existingSpreadsheet = getAdminEventSpreadsheet_(
        registry, String(draft.finalizedEventId)
      );
      return {
        draftId: draft.draftId,
        eventId: String(draft.finalizedEventId),
        sheetUrl: activitySheetUrl_(existingSpreadsheet),
        status: 'draft',
        alreadyFinalized: true
      };
    }
    var document = draft.document;
    var created = saveAdminEvent_(document.event, normalizedActor);
    document.sessions.forEach(function(session) {
      var sessionRequest = {};
      Object.keys(session).forEach(function(key) { sessionRequest[key] = session[key]; });
      sessionRequest.eventId = created.eventId;
      saveAdminSession_(sessionRequest, normalizedActor);
    });
    if (document.event.seatMode !== 'none') {
      saveAdminSeatPlan_({
        eventId: created.eventId,
        sessionId: document.seatPlan.sessionId,
        action: 'generate',
        mode: document.seatPlan.mode,
        zones: document.seatPlan.zones
      }, normalizedActor);
    }
    document.questions.forEach(function(question) {
      var questionRequest = {};
      Object.keys(question).forEach(function(key) {
        questionRequest[key] = question[key];
      });
      questionRequest.eventId = created.eventId;
      saveAdminQuestion_(questionRequest, normalizedActor);
    });
    draft.finalizedEventId = created.eventId;
    draft.updatedAt = new Date().toISOString();
    writeAdminRow_(registry, '活动草稿', draft.rowNumber, draft);
    appendAdminAudit_(
      registry,
      'FINALIZE_ACTIVITY_DRAFT',
      'activity_draft',
      draft.draftId,
      normalizedActor,
      { eventId: created.eventId }
    );
    return {
      draftId: draft.draftId,
      eventId: created.eventId,
      sheetUrl: created.sheetUrl,
      status: 'draft',
      alreadyFinalized: false
    };
  });
}

function deleteAdminDraft_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true) adminError_('CONFIRMATION_REQUIRED');
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    ensureActivityDraftRegistry_(registry);
    requireNoSwitchMaintenance_(registry);
    var draft = readActivityDraft_(registry, request.draftId);
    if (!draft) adminError_('NOT_FOUND');
    if (draft.finalizedEventId) adminError_('CONFLICT');
    getRequiredSheet_(registry, '活动草稿').deleteRow(draft.rowNumber);
    appendAdminAudit_(
      registry,
      'DELETE_ACTIVITY_DRAFT',
      'activity_draft',
      draft.draftId,
      normalizedActor,
      { title: draft.document.event.title }
    );
    return { draftId: draft.draftId, deleted: true };
  });
}

function deleteEmptyAdminEvent_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true) adminError_('CONFIRMATION_REQUIRED');
  if (typeof request.eventId !== 'string' || !request.eventId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    ensureActivityDraftRegistry_(registry);
    requireNoSwitchMaintenance_(registry);
    var eventId = request.eventId.trim();
    var catalogMatches = readAdminRows_(registry, '活动目录').filter(function(row) {
      return String(row.eventId || '').trim() === eventId;
    });
    if (catalogMatches.length !== 1) {
      adminError_(catalogMatches.length ? 'INTEGRITY_ERROR' : 'NOT_FOUND');
    }
    var catalog = catalogMatches[0];
    var spreadsheet = getAdminEventSpreadsheet_(registry, eventId);
    var hasHistory =
      readAdminRows_(spreadsheet, '参加者').length > 0 ||
      readAdminRows_(spreadsheet, '报名项目').some(function(row) {
        return String(row.eventId || '') === eventId;
      }) ||
      readAdminRows_(spreadsheet, '签到记录').some(function(row) {
        return String(row.eventId || '') === eventId;
      }) ||
      readAdminRows_(registry, '票券索引').some(function(row) {
        return String(row.eventId || '') === eventId;
      });
    if (hasHistory) adminError_('CONFLICT');
    var catalogSheet = getRequiredSheet_(registry, '活动目录');
    catalogSheet.deleteRow(catalog.rowNumber);
    try {
      DriveApp.getFileById(String(catalog.spreadsheetId)).setTrashed(true);
    } catch (error) {
      writeAdminRow_(registry, '活动目录', null, catalog);
      throw error;
    }
    try {
      appendAdminAudit_(
        registry,
        'DELETE_EMPTY_EVENT',
        'event',
        eventId,
        normalizedActor,
        { spreadsheetId: String(catalog.spreadsheetId) }
      );
    } catch (_ignored) {
      // The deletion is already complete and recoverable from Drive trash.
    }
    return { eventId: eventId, deleted: true, trashed: true };
  });
}

function getAdminDashboard_(payload) {
  var request = payload && typeof payload === 'object' && !Array.isArray(payload) ? payload : {};
  var search = typeof request.search === 'string' ? request.search.trim().toLowerCase() : '';
  if (Object.prototype.hasOwnProperty.call(request, 'eventId') &&
      (typeof request.eventId !== 'string' || !request.eventId.trim())) {
    adminError_('INVALID_REQUEST');
  }
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    ensureActivityDraftRegistry_(registry);
    var settings = getAdminSettings_(registry);
    var catalogEntries = readAdminRows_(registry, '活动目录');
    var drafts = readAdminRows_(registry, '活动草稿').filter(function(row) {
      return !String(row.finalizedEventId || '').trim();
    }).map(function(row) {
      var parsed;
      try {
        parsed = JSON.parse(String(row.payload || ''));
      } catch (_ignored) {
        adminError_('INTEGRITY_ERROR');
      }
      row.document = validateActivityDraftDocument_(parsed);
      return adminDraftProjection_(row);
    });
    var events = catalogEntries.map(function(entry) {
      var validated = validateEventCatalogEntry_(
        registry,
        entry,
        normalizeRoutingValue_(entry.eventId)
      );
      var projection = adminEventProjection_(validated, settings);
      projection.sheetUrl = activitySheetUrl_(validated.spreadsheetId);
      return projection;
    });
    var selectedEventId = typeof request.eventId === 'string'
      ? request.eventId.trim() : '';
    var spreadsheet = selectedEventId
      ? getAdminEventSpreadsheet_(registry, selectedEventId) : null;
    var sessions = spreadsheet ? readAdminRows_(spreadsheet, '场次').filter(function(session) {
      return String(session.eventId || '') === selectedEventId;
    }) : [];
    var seats = spreadsheet ? readAdminRows_(spreadsheet, '座位').filter(function(seat) {
      return String(seat.eventId || '') === selectedEventId;
    }) : [];
    var questions = spreadsheet ? readAdminRows_(spreadsheet, '报名问题').filter(function(question) {
      return String(question.eventId || '') === selectedEventId;
    }) : [];
    var participants = spreadsheet ? readAdminRows_(spreadsheet, '参加者') : [];
    var registrations = spreadsheet
      ? readAdminRows_(spreadsheet, '报名项目').filter(function(registration) {
        return String(registration.eventId || '') === selectedEventId;
      }) : [];
    var attendance = spreadsheet
      ? readAdminRows_(spreadsheet, '签到记录').filter(function(record) {
        return String(record.eventId || '') === selectedEventId;
      }) : [];
    var selectedCanDelete = Boolean(spreadsheet) &&
      participants.length === 0 &&
      registrations.length === 0 &&
      attendance.length === 0 &&
      !readAdminRows_(registry, '票券索引').some(function(route) {
        return String(route.eventId || '') === selectedEventId;
      });
    events.forEach(function(event) {
      event.canDelete = event.eventId === selectedEventId && selectedCanDelete;
    });
    var participantById = {};
    participants.forEach(function(participant) {
      participantById[participant.participantId] = participant;
    });
    var registrationGroupsById = {};
    var registrationGroups = [];
    registrations.forEach(function(registration) {
      var registrationId = String(registration.registrationId || '');
      var groupKey = registrationId || 'row:' + registration.rowNumber;
      var group = registrationGroupsById[groupKey];
      if (!group) {
        group = {
          registration: registration,
          sessionIds: [],
          seatChoices: [],
          answers: {}
        };
        registrationGroupsById[groupKey] = group;
        registrationGroups.push(group);
      }
      parseAdminStringArray_(registration.sessionIds).forEach(function(sessionId) {
        if (group.sessionIds.indexOf(sessionId) === -1) group.sessionIds.push(sessionId);
      });
      parseAdminStringArray_(registration.seatChoices).forEach(function(seatId) {
        if (group.seatChoices.indexOf(seatId) === -1) group.seatChoices.push(seatId);
      });
      var rowAnswers = parseAdminAnswers_(registration.answers).values;
      Object.keys(rowAnswers).forEach(function(key) { group.answers[key] = rowAnswers[key]; });
      if (String(registration.updatedAt || '') >
          String(group.registration.updatedAt || '')) {
        group.registration.updatedAt = registration.updatedAt;
      }
    });
    var records = [];
    registrationGroups.forEach(function(group) {
      var registration = group.registration;
      var participant = participantById[registration.participantId] || {};
      var haystack = [
        registration.registrationId, registration.ticketNumber, registration.eventId,
        participant.name, participant.phone, participant.email,
        group.sessionIds.join(' '), group.seatChoices.join(' '), JSON.stringify(group.answers)
      ].join(' ').toLowerCase();
      if (search && haystack.indexOf(search) === -1) return;
      records.push({
        registrationId: String(registration.registrationId || ''),
        eventId: String(registration.eventId || ''),
        ticketNumber: String(registration.ticketNumber || ''),
        status: String(registration.status || ''),
        participantName: maskAdminName_(participant.name),
        phone: maskAdminValue_(participant.phone),
        email: maskAdminValue_(participant.email),
        answers: maskAdminAnswers_(group.answers),
        sessionIds: group.sessionIds,
        seatChoices: group.seatChoices,
        createdAt: String(registration.createdAt || ''),
        updatedAt: String(registration.updatedAt || '')
      });
    });
    return {
      connection: {
        connected: true,
        sheetName: String(
          spreadsheet && spreadsheet.getName ? spreadsheet.getName() :
          registry.getName ? registry.getName() : 'Connected'
        )
      },
      drafts: drafts,
      events: events,
      sessions: sessions.map(function(session) { return adminSessionProjection_(session, settings); }),
      seats: seats.map(adminSeatProjection_),
      questions: questions.map(function(question) { return adminQuestionProjection_(question, settings); }),
      records: records,
      attendance: attendance.map(function(record) {
        return {
          checkInId: String(record.checkInId || ''),
          registrationId: String(record.registrationId || ''),
          eventId: String(record.eventId || ''),
          sessionId: String(record.sessionId || ''),
          checkedInAt: String(record.checkedInAt || ''),
          checkedInBy: maskAdminValue_(record.checkedInBy),
          status: String(record.status || '')
        };
      })
    };
  });
}

function getAdminEventSpreadsheet_(registry, eventId) {
  try {
    return getEventSpreadsheet_(registry, eventId);
  } catch (error) {
    if (error && error.publicCode === 'EVENT_NOT_FOUND') adminError_('NOT_FOUND');
    throw error;
  }
}

function saveAdminEvent_(payload, actor) {
  var request = requireAdminObject_(payload);
  var isNewEvent = !Object.prototype.hasOwnProperty.call(request, 'eventId');
  if (!isNewEvent &&
      (typeof request.eventId !== 'string' || !request.eventId.trim())) {
    adminError_('INVALID_REQUEST');
  }
  if (isNewEvent && Object.prototype.hasOwnProperty.call(request, 'spreadsheetId')) {
    adminError_('INVALID_REQUEST');
  }
  var normalizedActor = typeof actor === 'string' ? actor.trim().toLowerCase() : '';
  if (!normalizedActor) adminError_('ADMIN_ACTION_DENIED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    requireNoSwitchMaintenance_(registry);
    var spreadsheet = isNewEvent
      ? null : getAdminEventSpreadsheet_(registry, request.eventId.trim());
    var existing = isNewEvent
      ? null : findAdminRow_(spreadsheet, '活动', 'eventId', request.eventId.trim());
    if (!isNewEvent && !existing) adminError_('NOT_FOUND');
    if (request.action === 'reopen' && request.confirm !== true) {
      adminError_('CONFIRMATION_REQUIRED');
    }
    var now = new Date().toISOString();
    var eventId = existing ? existing.eventId : Utilities.getUuid();
    var status = adminField_(request, 'status', existing && existing.status, 'draft');
    if (request.action === 'archive') status = 'archived';
    if (request.action === 'close') status = request.closeStatus || 'ended';
    if (request.action === 'reopen') status = request.reopenStatus || 'open';
    status = String(status || '').toLowerCase();
    if (!ADMIN_EVENT_STATUSES_[status]) adminError_('INVALID_REQUEST');

    var title = adminTextField_(request, 'title', existing && existing.title, '');
    if (!title) adminError_('INVALID_REQUEST');
    var selectionMode = String(adminField_(
      request, 'selectionMode', existing && existing.selectionMode, 'free'
    )).toLowerCase();
    var seatMode = String(adminField_(
      request, 'seatMode', existing && existing.seatMode, 'none'
    )).toLowerCase();
    if (!ADMIN_SELECTION_MODES_[selectionMode] || !ADMIN_SEAT_MODES_[seatMode]) {
      adminError_('INVALID_REQUEST');
    }
    var minChoices = adminNonNegativeInteger_(
      adminField_(request, 'minChoices', existing && existing.minChoices, 0)
    );
    var maxChoices = adminNonNegativeInteger_(
      adminField_(request, 'maxChoices', existing && existing.maxChoices, 0)
    );
    if (maxChoices < minChoices) adminError_('INVALID_REQUEST');
    var opensAt = adminDateField_(adminField_(request, 'opensAt', existing && existing.opensAt, ''));
    var closesAt = adminDateField_(adminField_(request, 'closesAt', existing && existing.closesAt, ''));
    if (opensAt && closesAt && Date.parse(closesAt) <= Date.parse(opensAt)) {
      adminError_('INVALID_REQUEST');
    }
    var seatZonesValue = adminField_(request, 'seatZones', existing && existing.seatZones, []);
    var seatZones = parseAdminStringArray_(seatZonesValue);
    if (Array.isArray(seatZonesValue)) {
      seatZones = seatZonesValue.filter(function(zone) {
        return typeof zone === 'string' && zone.trim();
      }).map(function(zone) { return zone.trim(); });
    }
    var row = {
      eventId: eventId,
      title: title,
      description: adminTextField_(request, 'description', existing && existing.description, ''),
      status: status,
      opensAt: opensAt,
      closesAt: closesAt,
      location: adminTextField_(request, 'location', existing && existing.location, ''),
      selectionMode: selectionMode,
      minChoices: minChoices,
      maxChoices: maxChoices,
      seatMode: seatMode,
      seatZones: JSON.stringify(seatZones),
      createdAt: existing ? existing.createdAt : now,
      updatedAt: now
    };
    var settings = getAdminSettings_(registry);
    var policy = ensureAdminEventPolicy_(settings, eventId);
    copyAdminBooleanField_(request, policy, 'showOpeningCountdown');
    copyAdminBooleanField_(request, policy, 'showClosingCountdown');
    copyAdminBooleanField_(request, policy, 'cancellationEnabled');
    copyAdminBooleanField_(request, policy, 'seatExchangeEnabled');
    copyAdminBooleanField_(request, policy, 'seatHoldsEnabled');
    if (Object.prototype.hasOwnProperty.call(request, 'seatMapLabel')) {
      policy.seatMapLabel = adminTextField_(
        request, 'seatMapLabel', policy.seatMapLabel, '舞台 / 白板'
      ).slice(0, 80);
    }
    if (Object.prototype.hasOwnProperty.call(request, 'seatHoldMinutes')) {
      policy.seatHoldMinutes = adminPositiveInteger_(request.seatHoldMinutes);
    }
    if (Object.prototype.hasOwnProperty.call(request, 'registrationTimeLimitMinutes')) {
      policy.registrationTimeLimitMinutes = adminNonNegativeInteger_(
        request.registrationTimeLimitMinutes
      );
    }
    if (Object.prototype.hasOwnProperty.call(request, 'totalCapacity')) {
      policy.totalCapacity = adminNonNegativeInteger_(request.totalCapacity);
    }
    if (Object.prototype.hasOwnProperty.call(request, 'checkInMode')) {
      policy.checkInMode = adminCheckInMode_(request.checkInMode);
    }
    var result = adminEventProjection_(row, settings);
    if (isNewEvent) {
      spreadsheet = createActivitySpreadsheet_(
        eventId,
        title,
        normalizedActor
      );
    }
    result.sheetUrl = activitySheetUrl_(spreadsheet);
    if (request.action === 'reopen') {
      var registrationIds = {};
      readAdminRows_(spreadsheet, '报名项目').forEach(function(registration) {
        if (registration.eventId === eventId &&
            String(registration.status || '').toLowerCase() !== 'pending') {
          registrationIds[registration.registrationId] = true;
        }
      });
      result.registrationCount = Object.keys(registrationIds).length;
    }
    writeAdminRow_(spreadsheet, '活动', existing && existing.rowNumber, row);
    setAdminSettings_(registry, settings);
    appendAdminAudit_(
      spreadsheet,
      request.action ? String(request.action).toUpperCase() + '_EVENT' : (existing ? 'UPDATE_EVENT' : 'CREATE_EVENT'),
      'event',
      eventId,
      normalizedActor,
      { status: status }
    );
    upsertActivityCatalogEntry_(registry, row, spreadsheet);
    return result;
  });
}

function saveAdminSession_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (typeof request.eventId !== 'string' || !request.eventId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    requireNoSwitchMaintenance_(registry);
    var spreadsheet = getAdminEventSpreadsheet_(registry, request.eventId.trim());
    if (!findAdminRow_(spreadsheet, '活动', 'eventId', request.eventId.trim())) {
      adminError_('NOT_FOUND');
    }
    var existing = request.sessionId
      ? findAdminEventChildRow_(
        spreadsheet, '场次', 'sessionId', request.sessionId, request.eventId.trim()
      )
      : null;
    if (request.sessionId && !existing) adminError_('NOT_FOUND');
    var now = new Date().toISOString();
    var sessionId = existing ? existing.sessionId : Utilities.getUuid();
    var title = adminTextField_(request, 'title', existing && existing.title, '');
    var status = String(adminField_(request, 'status', existing && existing.status, 'draft')).toLowerCase();
    if (!title || (!ADMIN_EVENT_STATUSES_[status] && status !== 'inactive')) {
      adminError_('INVALID_REQUEST');
    }
    var startsAt = adminDateField_(adminField_(request, 'startsAt', existing && existing.startsAt, ''));
    var endsAt = adminDateField_(adminField_(request, 'endsAt', existing && existing.endsAt, ''));
    if ((startsAt || endsAt) && (!startsAt || !endsAt || Date.parse(endsAt) <= Date.parse(startsAt))) {
      adminError_('INVALID_REQUEST');
    }
    var row = {
      sessionId: sessionId,
      eventId: request.eventId.trim(),
      title: title,
      speaker: adminTextField_(request, 'speaker', existing && existing.speaker, ''),
      startsAt: startsAt,
      endsAt: endsAt,
      required: adminBooleanField_(request, 'required', existing && adminTruthy_(existing.required), false),
      capacity: adminNonNegativeInteger_(adminField_(request, 'capacity', existing && existing.capacity, 0)),
      status: status,
      createdAt: existing ? existing.createdAt : now,
      updatedAt: now
    };
    writeAdminRow_(spreadsheet, '场次', existing && existing.rowNumber, row);
    var settings = getAdminSettings_(registry);
    var sessionPolicy = ensureAdminSessionPolicy_(settings, row.eventId, sessionId);
    sessionPolicy.location = adminTextField_(
      request, 'location', sessionPolicy.location, ''
    );
    sessionPolicy.groupRule = adminTextField_(
      request, 'groupRule', sessionPolicy.groupRule, ''
    );
    refreshAdminEventDateSummary_(spreadsheet, settings, row.eventId);
    setAdminSettings_(registry, settings);
    appendAdminAudit_(
      spreadsheet, existing ? 'UPDATE_SESSION' : 'CREATE_SESSION',
      'session', sessionId, actor, { eventId: row.eventId }
    );
    return adminSessionProjection_(row, settings);
  });
}

function saveAdminQuestion_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (typeof request.eventId !== 'string' || !request.eventId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    requireNoSwitchMaintenance_(registry);
    var spreadsheet = getAdminEventSpreadsheet_(registry, request.eventId.trim());
    if (!findAdminRow_(spreadsheet, '活动', 'eventId', request.eventId.trim())) {
      adminError_('NOT_FOUND');
    }
    var existing = request.questionId
      ? findAdminEventChildRow_(
        spreadsheet, '报名问题', 'questionId', request.questionId, request.eventId.trim()
      )
      : null;
    if (request.questionId && !existing) adminError_('NOT_FOUND');
    var now = new Date().toISOString();
    var questionId = existing ? existing.questionId : Utilities.getUuid();
    var type = String(adminField_(request, 'type', existing && existing.type, 'text')).toLowerCase();
    var label = adminTextField_(request, 'label', existing && existing.label, '');
    if (!label || !ADMIN_QUESTION_TYPES_[type]) adminError_('INVALID_REQUEST');
    var status = String(adminField_(request, 'status', existing && existing.status, 'active')).toLowerCase();
    if (request.action === 'hide') status = 'inactive';
    if (request.action === 'show') status = 'active';
    if (status !== 'active' && status !== 'inactive') adminError_('INVALID_REQUEST');
    var choices = Array.isArray(request.options)
      ? request.options.filter(function(option) {
        return typeof option === 'string' && option.trim();
      }).map(function(option) { return option.trim(); })
      : parseAdminQuestionOptions_(existing && existing.options).choices;
    if ((type === 'select' || type === 'radio' || type === 'checkbox') && !choices.length) {
      adminError_('INVALID_REQUEST');
    }
    var validation = request.validation && typeof request.validation === 'object' &&
      !Array.isArray(request.validation) ? request.validation :
      parseAdminQuestionOptions_(existing && existing.options).validation;
    validation = normalizeAdminQuestionValidation_(type, validation, choices);
    var row = {
      questionId: questionId,
      eventId: request.eventId.trim(),
      label: label,
      type: type,
      required: adminBooleanField_(request, 'required', existing && adminTruthy_(existing.required), false),
      options: JSON.stringify(adminQuestionStorage_(choices, validation)),
      sortOrder: adminNonNegativeInteger_(adminField_(request, 'sortOrder', existing && existing.sortOrder, 0)),
      status: status,
      createdAt: existing ? existing.createdAt : now,
      updatedAt: now
    };
    var settings = getAdminSettings_(registry);
    var policy = ensureAdminEventPolicy_(settings, row.eventId);
    var inheritedIdentityFields = settings.registration &&
      Array.isArray(settings.registration.identityFields) ? settings.registration.identityFields : [];
    var eventQuestions = readAdminRows_(spreadsheet, '报名问题').filter(function(question) {
      return String(question.eventId || '') === row.eventId;
    });
    var configuredIdentityFields = (Array.isArray(policy.identityFields)
      ? policy.identityFields : inheritedIdentityFields).slice();
    var hadIdentityFields = configuredIdentityFields.length > 0;
    var identityFields = updateAdminFlagList_(
      configuredIdentityFields, questionId,
      adminBooleanField_(
        request, 'duplicateIdentity', adminListHas_(configuredIdentityFields, questionId), false
      )
    );
    if (hadIdentityFields || identityFields.length) {
      validateAdminIdentityFields_(
        identityFields,
        eventQuestions,
        row
      );
    }
    policy.identityFields = identityFields;
    policy.showOnTicketFields = updateAdminFlagList_(
      policy.showOnTicketFields, questionId,
      adminBooleanField_(request, 'showOnTicket', adminListHas_(policy.showOnTicketFields, questionId), false)
    );
    var semanticRole = adminQuestionSemanticRole_(
      request, policy, questionId, type, status
    );
    var removesIdentity = adminListHas_(configuredIdentityFields, questionId) &&
      !adminListHas_(identityFields, questionId);
    if (removesIdentity) {
      setAdminSettings_(registry, settings);
      writeAdminRow_(spreadsheet, '报名问题', existing && existing.rowNumber, row);
    } else {
      writeAdminRow_(spreadsheet, '报名问题', existing && existing.rowNumber, row);
      setAdminSettings_(registry, settings);
    }
    appendAdminAudit_(
      spreadsheet, existing ? 'UPDATE_QUESTION' : 'CREATE_QUESTION',
      'question', questionId, actor, { eventId: row.eventId, status: status }
    );
    var projection = adminQuestionProjection_(row, settings);
    projection.semanticRole = semanticRole;
    return projection;
  });
}

function saveAdminSeatPlan_(payload, actor) {
  var request = requireAdminObject_(payload);
  var action = String(request.action || 'generate').toLowerCase();
  if (typeof request.eventId !== 'string' || !request.eventId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    requireNoSwitchMaintenance_(registry);
    var eventId = request.eventId.trim();
    var spreadsheet = getAdminEventSpreadsheet_(registry, eventId);
    if (action === 'reserve' || action === 'close' || action === 'reopen') {
      var seat = findAdminEventChildRow_(
        spreadsheet, '座位', 'seatId', request.seatId, eventId
      );
      if (!seat) adminError_('NOT_FOUND');
      if (seat.holderRegistrationId && seat.status === 'registered') adminError_('CONFLICT');
      seat.status = action === 'reserve' ? 'reserved' : action === 'close' ? 'closed' : 'available';
      seat.updatedAt = new Date().toISOString();
      writeAdminRow_(spreadsheet, '座位', seat.rowNumber, seat);
      appendAdminAudit_(
        spreadsheet, action.toUpperCase() + '_SEAT', 'seat', seat.seatId, actor,
        { status: seat.status }
      );
      return adminSeatProjection_(seat);
    }
    if (action !== 'generate') {
      adminError_('INVALID_REQUEST');
    }
    var event = findAdminRow_(spreadsheet, '活动', 'eventId', eventId);
    if (!event) adminError_('NOT_FOUND');
    var sessionId = '';
    if (request.sessionId !== undefined && request.sessionId !== null &&
        request.sessionId !== '') {
      if (typeof request.sessionId !== 'string' || !request.sessionId.trim()) {
        adminError_('INVALID_REQUEST');
      }
      sessionId = request.sessionId.trim();
      if (!findAdminEventChildRow_(
        spreadsheet, '场次', 'sessionId', sessionId, eventId
      )) {
        adminError_('NOT_FOUND');
      }
    }
    var mode = String(request.mode || '').toLowerCase();
    if (!ADMIN_SEAT_MODES_[mode]) adminError_('INVALID_REQUEST');
    var zones = Array.isArray(request.zones) ? request.zones : [];
    if (mode !== 'none' && !zones.length) adminError_('INVALID_REQUEST');
    var now = new Date().toISOString();
    var existingSeats = readAdminRows_(spreadsheet, '座位').filter(function(seat) {
      return String(seat.eventId || '') === eventId;
    });
    var knownLabels = {};
    existingSeats.forEach(function(seat) {
      knownLabels[[seat.eventId, seat.sessionId, seat.label].join('|')] = true;
    });
    var created = [];
    var zoneNames = mode === 'none' ? [] : parseAdminStringArray_(event.seatZones);
    if (mode !== 'none') {
      zones.forEach(function(zone) {
        if (!zone || typeof zone !== 'object' || Array.isArray(zone)) adminError_('INVALID_REQUEST');
        var name = typeof zone.name === 'string' ? zone.name.trim() : '';
        var rowCount = adminPositiveInteger_(zone.rows);
        var seatCount = adminPositiveInteger_(zone.seatsPerRow);
        if (mode === 'zone' && !name) adminError_('INVALID_REQUEST');
        if (name && zoneNames.indexOf(name) === -1) zoneNames.push(name);
        for (var rowIndex = 1; rowIndex <= rowCount; rowIndex += 1) {
          for (var seatIndex = 1; seatIndex <= seatCount; seatIndex += 1) {
            var label = (name ? name + '-' : '') + rowIndex + '-' + seatIndex;
            var key = [event.eventId, sessionId, label].join('|');
            if (knownLabels[key]) continue;
            var createdSeat = {
              seatId: Utilities.getUuid(),
              eventId: event.eventId,
              sessionId: sessionId,
              label: label,
              zone: name,
              status: 'available',
              holderRegistrationId: '',
              createdAt: now,
              updatedAt: now
            };
            writeAdminRow_(spreadsheet, '座位', null, createdSeat);
            knownLabels[key] = true;
            created.push(createdSeat);
          }
        }
      });
    }
    event.seatMode = mode;
    event.seatZones = JSON.stringify(zoneNames);
    event.updatedAt = now;
    writeAdminRow_(spreadsheet, '活动', event.rowNumber, event);
    appendAdminAudit_(
      spreadsheet, 'SAVE_SEAT_PLAN', 'event', event.eventId, actor,
      { mode: mode, created: created.length }
    );
    upsertActivityCatalogEntry_(registry, event, spreadsheet);
    return { eventId: event.eventId, mode: mode, createdCount: created.length };
  });
}

function adminRecordAction_(payload, actor) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true) adminError_('CONFIRMATION_REQUIRED');
  var action = String(request.action || '').toLowerCase();
  if (typeof request.eventId !== 'string' || !request.eventId.trim() ||
      typeof request.registrationId !== 'string' || !request.registrationId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    requireNoSwitchMaintenance_(registry);
    var eventId = request.eventId.trim();
    var spreadsheet = getAdminEventSpreadsheet_(registry, eventId);
    var registrations = readAdminRows_(spreadsheet, '报名项目').filter(function(record) {
      return record.registrationId === request.registrationId.trim() &&
        String(record.eventId || '') === eventId;
    });
    if (!registrations.length) adminError_('NOT_FOUND');
    var seats = readAdminRows_(spreadsheet, '座位');
    var eventSeats = seats.filter(function(seat) {
      return String(seat.eventId || '') === eventId;
    });
    var now = new Date().toISOString();
    if (action === 'cancel_registration') {
      var route = requireAdminCancellationRoute_(
        registry, eventId, request.registrationId.trim(), registrations
      );
      upsertTicketRoute_(registry, {
        ticketNumber: route.ticketNumber,
        tokenDigest: route.tokenDigest,
        eventId: route.eventId,
        registrationId: route.registrationId,
        status: 'cancelled',
        createdAt: route.createdAt,
        updatedAt: now
      });
      registrations.forEach(function(record) {
        record.status = 'cancelled';
        record.updatedAt = now;
        writeAdminRow_(spreadsheet, '报名项目', record.rowNumber, record);
      });
      eventSeats.filter(function(seat) {
        return seat.holderRegistrationId === request.registrationId.trim() ||
          seat.holderRegistrationId === 'PENDING|' + request.registrationId.trim();
      }).forEach(function(seat) {
        seat.status = 'available';
        seat.holderRegistrationId = '';
        seat.updatedAt = now;
        writeAdminRow_(spreadsheet, '座位', seat.rowNumber, seat);
      });
    } else if (action === 'adjust_seat') {
      var target = findAdminEventChildRow_(
        spreadsheet, '座位', 'seatId', request.seatId, eventId
      );
      if (!target) adminError_('NOT_FOUND');
      var targetStatus = String(target.status || '').toLowerCase();
      if (target.holderRegistrationId ||
          (targetStatus !== 'available' && targetStatus !== 'open' && targetStatus !== 'reserved')) {
        adminError_('CONFLICT');
      }
      var registrationEventId = String(registrations[0].eventId || '');
      var selectedSessionIds = {};
      registrations.forEach(function(record) {
        if (String(record.eventId || '') !== registrationEventId) adminError_('CONFLICT');
        parseAdminStringArray_(record.sessionIds).forEach(function(sessionId) {
          selectedSessionIds[sessionId] = true;
        });
      });
      if (!registrationEventId || String(target.eventId || '') !== registrationEventId ||
          (target.sessionId && !selectedSessionIds[target.sessionId])) {
        adminError_('CONFLICT');
      }
      var oldSeats = eventSeats.filter(function(seat) {
        return seat.holderRegistrationId === request.registrationId.trim() &&
          (target.sessionId ? seat.sessionId === target.sessionId : !seat.sessionId);
      });
      if (oldSeats.length > 1) adminError_('CONFLICT');
      var affectedRegistrations = registrations.filter(function(record) {
        var recordSessionIds = parseAdminStringArray_(record.sessionIds);
        return !target.sessionId || recordSessionIds.indexOf(target.sessionId) !== -1;
      });
      var snapshots = snapshotAdminRows_(
        spreadsheet, '座位', [target]
      ).concat(snapshotAdminRows_(
        spreadsheet, '报名项目', affectedRegistrations
      ));
      try {
        target.status = 'registered';
        target.holderRegistrationId = request.registrationId.trim();
        target.updatedAt = now;
        writeAdminRow_(spreadsheet, '座位', target.rowNumber, target);
        affectedRegistrations.forEach(function(record) {
          var choices = parseAdminStringArray_(record.seatChoices).filter(function(seatId) {
            var oldSeat = eventSeats.filter(function(seat) {
              return seat.seatId === seatId;
            })[0];
            return !oldSeat ||
              (target.sessionId ? oldSeat.sessionId !== target.sessionId : !!oldSeat.sessionId);
          });
          if (choices.indexOf(target.seatId) === -1) choices.push(target.seatId);
          record.seatChoices = JSON.stringify(choices);
          record.updatedAt = now;
          writeAdminRow_(spreadsheet, '报名项目', record.rowNumber, record);
        });
      } catch (error) {
        var precommitRestoreFailures = restoreAdminSnapshots_(snapshots);
        if (precommitRestoreFailures.length) {
          appendAdminAuditSafely_(
            spreadsheet, 'ADMIN_SEAT_ADJUSTMENT_RECOVERY', 'registration',
            request.registrationId.trim(), actor,
            { seatId: String(request.seatId || ''), stage: 'precommit' }
          );
          adminError_('INTEGRITY_ERROR');
        }
        throw error;
      }
      try {
        oldSeats.forEach(function(seat) {
          seat.status = 'available';
          seat.holderRegistrationId = '';
          seat.updatedAt = now;
          writeAdminRow_(spreadsheet, '座位', seat.rowNumber, seat);
        });
      } catch (releaseError) {
        var releaseRestoreFailures = restoreAdminSnapshots_(snapshots);
        if (releaseRestoreFailures.length) {
          appendAdminAuditSafely_(
            spreadsheet, 'ADMIN_SEAT_ADJUSTMENT_RECOVERY', 'registration',
            request.registrationId.trim(), actor,
            { seatId: String(request.seatId || ''), stage: 'release' }
          );
          adminError_('INTEGRITY_ERROR');
        }
        throw releaseError;
      }
      appendAdminAuditSafely_(
        spreadsheet, action.toUpperCase(), 'registration', request.registrationId.trim(),
        actor, { seatId: String(request.seatId || '') }
      );
      return {
        registrationId: request.registrationId.trim(),
        action: action,
        status: 'completed'
      };
    } else {
      adminError_('INVALID_REQUEST');
    }
    appendAdminAudit_(
      spreadsheet, action.toUpperCase(), 'registration', request.registrationId.trim(),
      actor, { seatId: action === 'adjust_seat' ? String(request.seatId || '') : '' }
    );
    return { registrationId: request.registrationId.trim(), action: action, status: 'completed' };
  });
}

function requireAdminCancellationRoute_(registry, eventId, registrationId, registrations) {
  var ticketNumber = '';
  registrations.forEach(function(record) {
    var status = String(record.status || '').trim().toLowerCase();
    var candidate = String(record.ticketNumber || '').trim();
    if ((status !== 'active' && status !== 'confirmed') || !candidate ||
        (ticketNumber && ticketNumber !== candidate)) {
      adminError_('CONFLICT');
    }
    ticketNumber = candidate;
  });
  var route = getTicketRouteByNumber_(registry, ticketNumber);
  if (route.eventId !== eventId || route.registrationId !== registrationId ||
      route.ticketNumber !== ticketNumber ||
      String(route.status || '').toLowerCase() !== 'active') {
    adminError_('CONFLICT');
  }
  return route;
}

function testAdminSheetConnection_(payload) {
  var request = requireAdminObject_(payload);
  if (typeof request.spreadsheetId !== 'string' || !request.spreadsheetId.trim()) {
    adminError_('INVALID_REQUEST');
  }
  try {
    var spreadsheet = openSpreadsheetById_(request.spreadsheetId);
    validateAdminSpreadsheet_(spreadsheet);
    return {
      connected: true,
      sheetName: String(spreadsheet.getName ? spreadsheet.getName() : 'Connected')
    };
  } catch (error) {
    if (error && error.publicCode) throw error;
    adminError_('SHEET_CONNECTION_FAILED');
  }
}

function switchAdminSheet_(payload) {
  var request = requireAdminObject_(payload);
  if (request.confirm !== true) adminError_('CONFIRMATION_REQUIRED');
  return withScriptLock_(function() {
    var registry = getRootConfiguredSpreadsheet_();
    if (typeof request.spreadsheetId === 'string' && request.spreadsheetId.trim() &&
        (request.nonce === undefined || request.nonce === null || request.nonce === '')) {
      return stageAdminSheetSwitch_(registry, request.spreadsheetId.trim());
    }
    if (typeof request.nonce === 'string' && request.nonce &&
        (request.spreadsheetId === undefined || request.spreadsheetId === null ||
         request.spreadsheetId === '')) {
      return finalizeAdminSheetSwitch_(registry, request.nonce);
    }
    adminError_('INVALID_REQUEST');
  });
}

function stageAdminSheetSwitch_(registry, candidateSpreadsheetId) {
  var configuration = requireSwitchProbeConfiguration_();
  var existingMaintenance = getSharedSettingValue_(registry, SWITCH_MAINTENANCE);
  if (typeof existingMaintenance === 'string' && existingMaintenance.trim()) {
    var existing = parseAdminSwitchObject_(existingMaintenance);
    if (existing && isFutureSwitchTime_(existing.expiresAt)) adminError_('CONFLICT');
    clearAdminSwitchState_(registry);
  }

  var candidate;
  try {
    candidate = openSpreadsheetById_(candidateSpreadsheetId);
    validateAdminSpreadsheet_(candidate);
  } catch (error) {
    if (error && error.publicCode) throw error;
    adminError_('SHEET_CONNECTION_FAILED');
  }

  var expiresAt = new Date(Date.now() + SWITCH_PROBE_TTL_MS).toISOString();
  var nonce = createAdminSwitchNonce_(configuration.secret);
  try {
    setSharedSettingValue_(
      registry,
      SWITCH_MAINTENANCE,
      JSON.stringify({ nonce: nonce, expiresAt: expiresAt })
    );
    setSharedSettingValue_(
      registry,
      SWITCH_PROBE,
      JSON.stringify({
        nonce: nonce,
        candidateSpreadsheetId: candidateSpreadsheetId,
        expiresAt: expiresAt,
        createdAt: new Date().toISOString()
      })
    );
    setSharedSettingValue_(registry, SWITCH_PROBE_ACK, '');
  } catch (error) {
    try {
      clearAdminSwitchState_(registry);
    } catch (_ignored) {
      // A partially staged switch remains fail-closed until an administrator retries.
    }
    throw error;
  }
  return {
    state: 'probe_required',
    nonce: nonce,
    expiresAt: expiresAt,
    probeUrl: configuration.publicBackendUrl
  };
}

function finalizeAdminSheetSwitch_(registry, nonce) {
  var probe = parseAdminSwitchObject_(getSharedSettingValue_(registry, SWITCH_PROBE));
  var maintenance = parseAdminSwitchObject_(
    getSharedSettingValue_(registry, SWITCH_MAINTENANCE)
  );
  if (!probe || !maintenance || probe.nonce !== nonce || maintenance.nonce !== nonce) {
    adminError_('CONFLICT');
  }
  if (!isFutureSwitchTime_(probe.expiresAt) ||
      maintenance.expiresAt !== probe.expiresAt ||
      typeof probe.candidateSpreadsheetId !== 'string' ||
      !probe.candidateSpreadsheetId.trim()) {
    clearAdminSwitchState_(registry);
    adminError_('SHEET_CONNECTION_FAILED');
  }

  var ack = parseAdminSwitchObject_(getSharedSettingValue_(registry, SWITCH_PROBE_ACK));
  var configuration = requireSwitchProbeConfiguration_();
  if (!isValidAdminSwitchAck_(ack, probe, configuration.secret)) {
    clearAdminSwitchState_(registry);
    adminError_('SHEET_CONNECTION_FAILED');
  }

  var candidate;
  try {
    candidate = openSpreadsheetById_(probe.candidateSpreadsheetId);
    validateAdminSpreadsheet_(candidate);
  } catch (error) {
    clearAdminSwitchState_(registry);
    if (error && error.publicCode) throw error;
    adminError_('SHEET_CONNECTION_FAILED');
  }

  var pointer = String(registry.getId()) === probe.candidateSpreadsheetId
    ? ''
    : probe.candidateSpreadsheetId;
  setSharedSettingValue_(registry, ACTIVE_SPREADSHEET_ID, pointer);
  setSharedSettingValue_(registry, SWITCH_MAINTENANCE, '');
  try {
    setSharedSettingValue_(registry, SWITCH_PROBE, '');
    setSharedSettingValue_(registry, SWITCH_PROBE_ACK, '');
  } catch (_ignored) {
    // Maintenance is already cleared after publication; stale probe rows are inert.
  }
  return {
    connected: true,
    sheetName: String(candidate.getName ? candidate.getName() : 'Connected'),
    warning: '旧数据仍保留在原数据表中；系统不会自动迁移任何数据。'
  };
}

function requireSwitchProbeConfiguration_() {
  var properties = PropertiesService.getScriptProperties();
  var secret = properties.getProperty(SWITCH_PROBE_SHARED_SECRET);
  var publicBackendUrl = properties.getProperty(PUBLIC_BACKEND_URL);
  if (typeof secret !== 'string' || secret.length < 32 ||
      typeof publicBackendUrl !== 'string' ||
      !/^https:\/\/script\.google\.com\/macros\/s\/[^/?#]+\/exec$/.test(publicBackendUrl)) {
    adminError_('SHEET_CONNECTION_FAILED');
  }
  return { secret: secret, publicBackendUrl: publicBackendUrl };
}

function createAdminSwitchNonce_(secret) {
  var randomInput = Utilities.getUuid() + '\n' + Utilities.getUuid();
  return Utilities.base64EncodeWebSafe(
    Utilities.computeHmacSha256Signature(randomInput, secret)
  );
}

function isValidAdminSwitchAck_(ack, probe, secret) {
  if (!ack || ack.nonce !== probe.nonce || ack.expiresAt !== probe.expiresAt ||
      typeof ack.verifiedAt !== 'string' || typeof ack.signature !== 'string') {
    return false;
  }
  var verifiedAt = new Date(ack.verifiedAt).getTime();
  var expiresAt = new Date(probe.expiresAt).getTime();
  if (!isFinite(verifiedAt) || !isFinite(expiresAt) || verifiedAt > expiresAt) return false;
  return ack.signature === signAdminSwitchAck_(
    probe.nonce,
    probe.candidateSpreadsheetId,
    probe.expiresAt,
    secret
  );
}

function signAdminSwitchAck_(nonce, candidateSpreadsheetId, expiresAt, secret) {
  return Utilities.base64EncodeWebSafe(
    Utilities.computeHmacSha256Signature(
      nonce + '\n' + candidateSpreadsheetId + '\n' + expiresAt,
      secret
    )
  );
}

function parseAdminSwitchObject_(serialized) {
  if (typeof serialized !== 'string' || !serialized.trim()) return null;
  try {
    var value = JSON.parse(serialized);
    return value && typeof value === 'object' && !Array.isArray(value) ? value : null;
  } catch (_ignored) {
    return null;
  }
}

function isFutureSwitchTime_(serialized) {
  if (typeof serialized !== 'string') return false;
  var time = new Date(serialized).getTime();
  return isFinite(time) && time > Date.now();
}

function clearAdminSwitchState_(registry) {
  setSharedSettingValue_(registry, SWITCH_MAINTENANCE, '');
  setSharedSettingValue_(registry, SWITCH_PROBE, '');
  setSharedSettingValue_(registry, SWITCH_PROBE_ACK, '');
}

function getAdminSourceBundles_(payload) {
  if (payload !== undefined && payload !== null &&
      (typeof payload !== 'object' || Array.isArray(payload))) {
    adminError_('INVALID_REQUEST');
  }
  return {
    publicBackend: PUBLIC_BACKEND_SOURCE_BUNDLE_,
    staffAdmin: STAFF_ADMIN_SOURCE_BUNDLE_
  };
}

function validateAdminSpreadsheet_(spreadsheet) {
  Object.keys(STAFF_SHEET_DEFINITIONS).forEach(function(sheetName) {
    var sheet = spreadsheet.getSheetByName(sheetName);
    if (!sheet || sheet.getLastRow() < 1) adminError_('SHEET_CONNECTION_FAILED');
    var expected = STAFF_SHEET_DEFINITIONS[sheetName];
    var actual = sheet.getRange(1, 1, 1, expected.length).getValues()[0];
    if (!expected.every(function(header, index) { return actual[index] === header; })) {
      adminError_('SHEET_CONNECTION_FAILED');
    }
  });
  return true;
}

function requireAdminObject_(payload) {
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
    adminError_('INVALID_REQUEST');
  }
  return payload;
}

function readAdminRows_(spreadsheet, sheetName) {
  var sheet = getRequiredSheet_(spreadsheet, sheetName);
  if (sheet.getLastRow() <= 1) return [];
  var headers = STAFF_SHEET_DEFINITIONS[sheetName];
  return sheet.getRange(2, 1, sheet.getLastRow() - 1, headers.length).getValues().map(function(values, index) {
    var row = { rowNumber: index + 2 };
    headers.forEach(function(header, column) { row[header] = values[column]; });
    return row;
  });
}

function findAdminRow_(spreadsheet, sheetName, key, value) {
  return readAdminRows_(spreadsheet, sheetName).filter(function(row) {
    return row[key] === value;
  })[0] || null;
}

function findAdminEventChildRow_(spreadsheet, sheetName, key, value, eventId) {
  var matches = readAdminRows_(spreadsheet, sheetName).filter(function(row) {
    return row[key] === value;
  });
  if (matches.length > 1) adminError_('INTEGRITY_ERROR');
  if (!matches.length) return null;
  if (String(matches[0].eventId || '') !== String(eventId || '')) {
    adminError_('CONFLICT');
  }
  return matches[0];
}

function writeAdminRow_(spreadsheet, sheetName, rowNumber, row) {
  var sheet = getRequiredSheet_(spreadsheet, sheetName);
  var values = normalizeRow_(sheetName, row);
  var targetRow = rowNumber || sheet.getLastRow() + 1;
  if (typeof journalAdminWrite_ === 'function') {
    journalAdminWrite_(
      sheet,
      targetRow,
      values.length,
      !rowNumber && targetRow > sheet.getLastRow()
    );
  }
  sheet.getRange(targetRow, 1, 1, values.length).setValues([values]);
  return targetRow;
}

function snapshotAdminRows_(spreadsheet, sheetName, rows) {
  var sheet = getRequiredSheet_(spreadsheet, sheetName);
  return rows.map(function(row) {
    return {
      sheet: sheet,
      rowNumber: row.rowNumber,
      values: normalizeRow_(sheetName, row)
    };
  });
}

function restoreAdminSnapshots_(snapshots) {
  var failures = [];
  snapshots.forEach(function(snapshot) {
    try {
      snapshot.sheet.getRange(
        snapshot.rowNumber, 1, 1, snapshot.values.length
      ).setValues([snapshot.values]);
    } catch (error) {
      failures.push(error);
    }
  });
  return failures;
}

function appendAdminAudit_(spreadsheet, action, entityType, entityId, actor, details) {
  writeAdminRow_(spreadsheet, '操作记录', null, {
    auditId: Utilities.getUuid(),
    action: action,
    entityType: entityType,
    entityId: entityId,
    actor: actor,
    details: JSON.stringify(details || {}),
    createdAt: new Date().toISOString()
  });
}

function appendAdminAuditSafely_(spreadsheet, action, entityType, entityId, actor, details) {
  try {
    appendAdminAudit_(spreadsheet, action, entityType, entityId, actor, details);
    return null;
  } catch (error) {
    return error;
  }
}

function adminField_(source, key, existing, fallback) {
  if (Object.prototype.hasOwnProperty.call(source, key)) return source[key];
  if (existing !== undefined && existing !== null && existing !== '') return existing;
  return fallback;
}

function adminTextField_(source, key, existing, fallback) {
  var value = adminField_(source, key, existing, fallback);
  if (value === undefined || value === null) return '';
  if (typeof value !== 'string' || value.length > 5000) adminError_('INVALID_REQUEST');
  return value.trim();
}

function adminBooleanField_(source, key, existing, fallback) {
  if (!Object.prototype.hasOwnProperty.call(source, key)) {
    return existing === undefined || existing === null ? fallback : existing === true;
  }
  if (typeof source[key] !== 'boolean') adminError_('INVALID_REQUEST');
  return source[key];
}

function copyAdminBooleanField_(source, target, key) {
  if (!Object.prototype.hasOwnProperty.call(source, key)) return;
  if (typeof source[key] !== 'boolean') adminError_('INVALID_REQUEST');
  target[key] = source[key];
}

function adminDateField_(value) {
  if (value === '' || value === undefined || value === null) return '';
  var text = String(value).trim();
  if (!text || !isFinite(Date.parse(text))) adminError_('INVALID_REQUEST');
  return text;
}

function adminNonNegativeInteger_(value) {
  var number = Number(value);
  if (!isFinite(number) || number < 0 || Math.floor(number) !== number) {
    adminError_('INVALID_REQUEST');
  }
  return number;
}

function adminPositiveInteger_(value) {
  var number = adminNonNegativeInteger_(value);
  if (number < 1) adminError_('INVALID_REQUEST');
  return number;
}

function adminCheckInMode_(value) {
  var normalized = String(value || '').toLowerCase();
  if (normalized !== 'session' && normalized !== 'event' && normalized !== 'none') {
    adminError_('INVALID_REQUEST');
  }
  return normalized;
}

function adminTruthy_(value) {
  return value === true || value === 1 || String(value).toLowerCase() === 'true' || String(value) === '1';
}

function ensureAdminEventPolicy_(settings, eventId) {
  if (!settings.registration || typeof settings.registration !== 'object' ||
      Array.isArray(settings.registration)) settings.registration = {};
  if (!settings.registration.events || typeof settings.registration.events !== 'object' ||
      Array.isArray(settings.registration.events)) settings.registration.events = {};
  if (!settings.registration.events[eventId] ||
      typeof settings.registration.events[eventId] !== 'object' ||
      Array.isArray(settings.registration.events[eventId])) {
    settings.registration.events[eventId] = {};
  }
  return settings.registration.events[eventId];
}

function ensureAdminSessionPolicy_(settings, eventId, sessionId) {
  var eventPolicy = ensureAdminEventPolicy_(settings, eventId);
  if (!eventPolicy.sessions || typeof eventPolicy.sessions !== 'object' ||
      Array.isArray(eventPolicy.sessions)) eventPolicy.sessions = {};
  if (!eventPolicy.sessions[sessionId] || typeof eventPolicy.sessions[sessionId] !== 'object' ||
      Array.isArray(eventPolicy.sessions[sessionId])) eventPolicy.sessions[sessionId] = {};
  return eventPolicy.sessions[sessionId];
}

function refreshAdminEventDateSummary_(spreadsheet, settings, eventId) {
  var starts = [];
  var ends = [];
  readAdminRows_(spreadsheet, '场次').forEach(function(session) {
    if (String(session.eventId || '') !== eventId) return;
    var start = Date.parse(session.startsAt);
    var end = Date.parse(session.endsAt);
    if (!isFinite(start) || !isFinite(end) || end <= start) return;
    starts.push(start);
    ends.push(end);
  });
  var policy = ensureAdminEventPolicy_(settings, eventId);
  policy.eventStartsAt = starts.length
    ? new Date(Math.min.apply(null, starts)).toISOString() : '';
  policy.eventEndsAt = ends.length
    ? new Date(Math.max.apply(null, ends)).toISOString() : '';
}

function adminEventProjection_(event, settings) {
  var policy = ensureAdminEventPolicy_(settings || {}, event.eventId);
  return {
    eventId: String(event.eventId || ''),
    title: String(event.title || ''),
    description: String(event.description || ''),
    status: String(event.status || ''),
    opensAt: String(event.opensAt || ''),
    closesAt: String(event.closesAt || ''),
    location: String(event.location || ''),
    selectionMode: String(event.selectionMode || ''),
    minChoices: Number(event.minChoices || 0),
    maxChoices: Number(event.maxChoices || 0),
    seatMode: String(event.seatMode || 'none'),
    seatMapLabel: String(policy.seatMapLabel || '舞台 / 白板'),
    seatZones: parseAdminStringArray_(event.seatZones),
    showOpeningCountdown: policy.showOpeningCountdown === true,
    showClosingCountdown: policy.showClosingCountdown === true,
    cancellationEnabled: policy.cancellationEnabled === true,
    seatExchangeEnabled: policy.seatExchangeEnabled === true,
    seatHoldsEnabled: policy.seatHoldsEnabled === true,
    seatHoldMinutes: adminPositiveInteger_(policy.seatHoldMinutes || 5),
    registrationTimeLimitMinutes: adminNonNegativeInteger_(
      policy.registrationTimeLimitMinutes === undefined
        ? 5 : policy.registrationTimeLimitMinutes
    ),
    totalCapacity: adminNonNegativeInteger_(
      policy.totalCapacity === undefined ? 0 : policy.totalCapacity
    ),
    checkInMode: adminCheckInMode_(policy.checkInMode || 'session'),
    createdAt: String(event.createdAt || ''),
    updatedAt: String(event.updatedAt || '')
  };
}

function adminSessionProjection_(session, settings) {
  var eventPolicy = ensureAdminEventPolicy_(settings || {}, session.eventId);
  var policy = eventPolicy.sessions && eventPolicy.sessions[session.sessionId] || {};
  return {
    sessionId: String(session.sessionId || ''),
    eventId: String(session.eventId || ''),
    title: String(session.title || ''),
    speaker: String(session.speaker || ''),
    startsAt: String(session.startsAt || ''),
    endsAt: String(session.endsAt || ''),
    location: String(policy.location || ''),
    capacity: Number(session.capacity || 0),
    required: adminTruthy_(session.required),
    groupRule: String(policy.groupRule || ''),
    status: String(session.status || ''),
    createdAt: String(session.createdAt || ''),
    updatedAt: String(session.updatedAt || '')
  };
}

function adminSeatProjection_(seat) {
  return {
    seatId: String(seat.seatId || ''),
    eventId: String(seat.eventId || ''),
    sessionId: String(seat.sessionId || ''),
    label: String(seat.label || ''),
    zone: String(seat.zone || ''),
    status: String(seat.status || ''),
    holderRegistrationId: seat.holderRegistrationId ? 'assigned' : '',
    createdAt: String(seat.createdAt || ''),
    updatedAt: String(seat.updatedAt || '')
  };
}

function adminQuestionProjection_(question, settings) {
  var policy = ensureAdminEventPolicy_(settings || {}, question.eventId);
  var identityFields = Array.isArray(policy.identityFields) ? policy.identityFields :
    (settings && settings.registration && Array.isArray(settings.registration.identityFields)
      ? settings.registration.identityFields : []);
  var parsed = parseAdminQuestionOptions_(question.options);
  var semanticRole = '';
  var fieldRoles = policy.fieldRoles && typeof policy.fieldRoles === 'object' &&
    !Array.isArray(policy.fieldRoles) ? policy.fieldRoles : {};
  Object.keys(fieldRoles).some(function(role) {
    if (fieldRoles[role] !== question.questionId) return false;
    semanticRole = role;
    return true;
  });
  return {
    questionId: String(question.questionId || ''),
    eventId: String(question.eventId || ''),
    label: String(question.label || ''),
    type: String(question.type || ''),
    required: adminTruthy_(question.required),
    options: parsed.choices,
    validation: parsed.validation,
    sortOrder: Number(question.sortOrder || 0),
    status: String(question.status || ''),
    showOnTicket: adminListHas_(policy.showOnTicketFields, question.questionId),
    duplicateIdentity: adminListHas_(identityFields, question.questionId),
    semanticRole: semanticRole,
    createdAt: String(question.createdAt || ''),
    updatedAt: String(question.updatedAt || '')
  };
}

function normalizeAdminQuestionValidation_(type, source, choices) {
  var validation = source && typeof source === 'object' && !Array.isArray(source)
    ? source : {};
  var allowed = {
    minLength: true, maxLength: true, min: true, max: true,
    pattern: true, minSelections: true, maxSelections: true
  };
  var normalized = {};
  Object.keys(validation).forEach(function(key) {
    if (!allowed[key]) adminError_('INVALID_REQUEST');
    var value = validation[key];
    if (key === 'pattern') {
      if (typeof value !== 'string' || value.length > 500) adminError_('INVALID_REQUEST');
      try { new RegExp(value); } catch (_invalidPattern) { adminError_('INVALID_REQUEST'); }
      normalized[key] = value;
      return;
    }
    var number = Number(value);
    if (!isFinite(number)) adminError_('INVALID_REQUEST');
    if (key === 'minLength' || key === 'maxLength' ||
        key === 'minSelections' || key === 'maxSelections') {
      if (number < 0 || Math.floor(number) !== number) adminError_('INVALID_REQUEST');
    }
    normalized[key] = number;
  });
  if (normalized.minLength !== undefined && normalized.maxLength !== undefined &&
      normalized.minLength > normalized.maxLength) adminError_('INVALID_REQUEST');
  if (normalized.min !== undefined && normalized.max !== undefined &&
      normalized.min > normalized.max) adminError_('INVALID_REQUEST');
  if (normalized.minSelections !== undefined && normalized.maxSelections !== undefined &&
      normalized.minSelections > normalized.maxSelections) adminError_('INVALID_REQUEST');
  if ((normalized.minSelections !== undefined || normalized.maxSelections !== undefined) &&
      type !== 'checkbox') adminError_('INVALID_REQUEST');
  if (normalized.maxSelections !== undefined && normalized.maxSelections > choices.length) {
    adminError_('INVALID_REQUEST');
  }
  return normalized;
}

function adminQuestionStorage_(choices, validation) {
  var result = { choices: choices.slice() };
  Object.keys(validation || {}).forEach(function(key) { result[key] = validation[key]; });
  return result;
}

function adminQuestionSemanticRole_(request, policy, questionId, type, status) {
  if (!policy.fieldRoles || typeof policy.fieldRoles !== 'object' ||
      Array.isArray(policy.fieldRoles)) policy.fieldRoles = {};
  var existingRole = '';
  Object.keys(policy.fieldRoles).some(function(role) {
    if (policy.fieldRoles[role] !== questionId) return false;
    existingRole = role;
    return true;
  });
  var requested = Object.prototype.hasOwnProperty.call(request, 'semanticRole')
    ? String(request.semanticRole || '').trim().toLowerCase() : existingRole;
  if (status !== 'active') requested = '';
  var roleTypes = {
    name: { text: true, textarea: true },
    email: { email: true },
    phone: { tel: true }
  };
  if (requested && (!roleTypes[requested] || !roleTypes[requested][type])) {
    adminError_('INVALID_REQUEST');
  }
  Object.keys(policy.fieldRoles).forEach(function(role) {
    if (policy.fieldRoles[role] === questionId) delete policy.fieldRoles[role];
  });
  if (requested) policy.fieldRoles[requested] = questionId;
  return requested;
}

function parseAdminQuestionOptions_(serialized) {
  if (!serialized) return { choices: [], validation: {} };
  try {
    var parsed = typeof serialized === 'string' ? JSON.parse(serialized) : serialized;
    if (Array.isArray(parsed)) return { choices: parsed, validation: {} };
    if (!parsed || typeof parsed !== 'object') return { choices: [], validation: {} };
    var validation = parsed.validation && typeof parsed.validation === 'object' &&
      !Array.isArray(parsed.validation) ? parsed.validation : {};
    ['minLength', 'maxLength', 'min', 'max', 'pattern', 'minSelections', 'maxSelections']
      .forEach(function(key) {
        if (parsed[key] !== undefined) validation[key] = parsed[key];
      });
    return {
      choices: Array.isArray(parsed.choices) ? parsed.choices :
        (Array.isArray(parsed.options) ? parsed.options : []),
      validation: validation
    };
  } catch (_ignored) {
    return { choices: [], validation: {} };
  }
}

function parseAdminStringArray_(serialized) {
  if (Array.isArray(serialized)) {
    return serialized.filter(function(value) { return typeof value === 'string'; });
  }
  try {
    var parsed = JSON.parse(serialized || '[]');
    return Array.isArray(parsed)
      ? parsed.filter(function(value) { return typeof value === 'string'; })
      : [];
  } catch (_ignored) {
    return [];
  }
}

function parseAdminAnswers_(serialized) {
  try {
    var parsed = typeof serialized === 'string' ? JSON.parse(serialized) : serialized;
    if (parsed && typeof parsed === 'object' && parsed.values &&
        typeof parsed.values === 'object' && !Array.isArray(parsed.values)) return parsed;
    return { values: parsed && typeof parsed === 'object' ? parsed : {} };
  } catch (_ignored) {
    return { values: {} };
  }
}

function maskAdminName_(value) {
  var text = String(value || '').trim();
  if (!text) return '';
  return text.slice(0, 1) + new Array(Math.max(2, text.length)).join('*');
}

function maskAdminValue_(value) {
  if (typeof value === 'boolean') return '****';
  var text = String(value === undefined || value === null ? '' : value).trim();
  if (!text) return '';
  if (text.indexOf('@') !== -1) {
    var parts = text.split('@');
    return parts[0].slice(0, 1) + '***@' + parts.slice(1).join('@');
  }
  return text.length <= 4 ? '****' : text.slice(0, 2) + '****' + text.slice(-2);
}

function maskAdminAnswers_(answers) {
  var masked = {};
  Object.keys(answers || {}).forEach(function(key) {
    var value = answers[key];
    if (Array.isArray(value)) {
      masked[key] = value.map(maskAdminValue_);
    } else {
      masked[key] = maskAdminValue_(value);
    }
  });
  return masked;
}

function adminListHas_(values, value) {
  return Array.isArray(values) && values.indexOf(value) !== -1;
}

function updateAdminFlagList_(values, value, enabled) {
  var list = Array.isArray(values) ? values.filter(function(item) {
    return typeof item === 'string' && item !== value;
  }) : [];
  if (enabled) list.push(value);
  return list;
}

function validateAdminIdentityFields_(identityFields, questions, candidate) {
  if (!Array.isArray(identityFields)) adminError_('CONFLICT');
  if (!identityFields.length) return;
  var questionsById = {};
  questions.forEach(function(question) {
    if (question.eventId === candidate.eventId) questionsById[question.questionId] = question;
  });
  questionsById[candidate.questionId] = candidate;
  var seen = {};
  identityFields.forEach(function(questionId) {
    if (typeof questionId !== 'string' || !questionId || seen[questionId]) {
      adminError_('CONFLICT');
    }
    seen[questionId] = true;
    var question = questionsById[questionId];
    if (!question || String(question.status || '').toLowerCase() !== 'active' ||
        !adminTruthy_(question.required)) {
      adminError_('CONFLICT');
    }
  });
}
